### PR TITLE
Support name attribute for collisions

### PR DESCRIPTION
**Pull request by nlamprian**
I added the name attribute in Collision, which interestingly enough, was only present in Visual.

### CODE REVIEW

**Comment by jspricke** [comment]
@clalancette could we get this merged? Thanks!

**Comment by nlamprian** [comment]
Is someone maintaining the package? If so, please review the PR. As it is, specifying a name in a collision tag appears as an error that confuses.

**Comment by sloretz** [comment]
Context: 
* The `urdf` schema allows a `name` attribute on collisions, but is commented as undocumented: https://github.com/ros/urdfdom/blob/99c6f58120a5dfd1f9fc36419cd9f9aa0246efde/xsd/urdf.xsd#L146
* `urdfdom_headers` `urdf::Collision` type has a `name` field: https://github.com/ros/urdfdom_headers/blob/8ec38993c21c6913602b9519ca07e4e018af88b5/urdf_model/include/urdf_model/link.h#L183
* `urdfdom` does parse and populate the `name` attribute on a Collision: https://github.com/ros/urdfdom/blob/99c6f58120a5dfd1f9fc36419cd9f9aa0246efde/urdf_parser/src/link.cpp#L408-L410

Since the C++ API supports this, it seems like a good idea to me to add it to the Python API

**Review by sloretz — APPROVED** [review]
I didn't try this locally, but the change and new test looks the same as how the `name` attribute is handled and tested for `<visual>` tags.

**Comment by brinij** [comment]
@clalancette Could you please review this PR so it can be merged soon? That would be really helpful! Thanks!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
