### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by timonegk**
Some small changes to make urdf_parser_py able to run in python3.

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
All of the changes look OK to me (in that they probably won't break anything on python 2), with the possible exception of the addition of `.decode()`.  I've had trouble with that before; have you tested on both python2 and python3 with that in place?

**Comment by timonegk** [comment]
Even though `.decode()` would work, I think that providing the `encoding='unicode'` parameter is the better solution because it is easier to understand. In the background, both are the same (see [the lxml source](https://github.com/lxml/lxml/blob/master/src/lxml/serializer.pxi#L144)). I will edit my commit in a second.

**Comment by eacousineau** [comment]
Should we perhaps revive Travis CI for Python3-only testing, if we want to vet PRs to ensure that they don't break anything? (at least until the buildfarm supports that configuration?)

**Comment by nzlz** [comment]
Hey guys, could you accept this PR? I faced the same issue and had to create a solution like the one posted here. Using the official repo is always more convenient.

I can create the PR to a new branch if this is the issue.

**Review by clalancette — APPROVED** [review]
This looks good to me.

@sloretz unless you have objections here, I'll merge this later today.

**Pull request merged**
